### ISSUE TITLE
Allow users to define "high" and "low" for the focal variable and the outcome variable

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/plotmodsem#14]
# To-Do

- [x] For +/- SD, allows users to decide how many SD from the means. (e032e85a83f242ffd9f340a96531a8623045362a)
- [x] For percentiles, allows users to decide the percentiles. (7cfee6cb0b016b9cb51e226b40de5d0f6e416154)
- [x] For percentiles, allows users to set the SD for a normal distribution and the function will determine the corresponding percentiles. (5ca75e4253cd3a8edd600b4619c53716094a2d5c)
