### ISSUE TITLE
Indicate +/- 1 SD and 2SD for the focal variable

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/plotmodsem#15]
# Note

E.g., add vertical dash lines, or shade the regions.

# To-Do
- [x] Write a test (50d9c817b831ccecedfe6de1d80cb91149fc7ecd)
- [x] Revise `plotmod` (50d9c817b831ccecedfe6de1d80cb91149fc7ecd)
- [x] Test `plotmod` (50d9c817b831ccecedfe6de1d80cb91149fc7ecd)
