### ISSUE TITLE
Write the function to identify product terms

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/plotmodsem#3]
# To-Do
- [x] Write the test first. (3e47491475329b4234282c7bfc32f9112d1bb4d1)
- [x] Write the function. (3e47491475329b4234282c7bfc32f9112d1bb4d1)
- [x] Test the function. (3e47491475329b4234282c7bfc32f9112d1bb4d1)
