### ISSUE TITLE
Write the function to plot the moderation effect

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/plotmodsem#4]
# To-Do
- [x] Write the test first. (1eb24f40652e0149a55b8c63a20dad7d0b1375ed)
- [x] Write the function. (1eb24f40652e0149a55b8c63a20dad7d0b1375ed)
- [x] Test the function. (1eb24f40652e0149a55b8c63a20dad7d0b1375ed)
