### ISSUE TITLE
Test the package for release

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/plotmodsem#6]
# To-Do
- [x] Test the package.
- [x] Check the documentation.
- [x] Check the package.
